### ISSUE TITLE
Create .gitignore file

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#1]
Files like .DS_Store should not be pushed to the repo. Add them to .gitignore (https://help.github.com/en/articles/ignoring-files)

**Comment by ImaneChafi** [comment]
Perfect! I added the .DS_Store to the .gitignore https://github.com/DDMAL/mei-mapping-tool/commit/a13247890bc5b8693de7a5b7db891fd2b3da65ee
