### ISSUE TITLE
Change UI column name

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#11]
SIMSSA MEI Mapping App -> Squiggle to MEI mapping tool
Classification name -> Classifier label
MEI encoding -> MEI snippet
Text Description -> Name, Folio, Description

**Comment by ImaneChafi** [comment]
For the text description, do we want to have 3 separate input boxes for the name, folio and description or are they all going to be in one input box?

**Comment by vigliensoni** [comment]
These are conceptually image examples of the same encoding, so I would have
three input boxes for the specific fields. Having said that, with this
approach the user won't be able to add the folio where each example
appears. A user should create a different row if this is wanted.

**Comment by ImaneChafi** [comment]
Perfect! I'll add a button for adding different folios and also for adding name classifiers or deleting them.
