### ISSUE TITLE
Upload Word document with images

### ISSUE THREAD

**Issue by ImaneChafi** [DDMAL/mei-mapping-tool#113]
Have an upload word document that creates neumes with the images from a word table.

**Comment by fujinaga** [comment]
It doesn't have to be directly from Word. It could be saved as, say, HTML from Word then upload the HTML file. You can also assume that the table is in a pre-defined order.

**Comment by ImaneChafi** [comment]
Perfect, I'll change it for an html upload. Should the upload in csv button still be there even if users can now directly upload .xlsx or .xls files?

Best regards,
Imane Chafi
________________________________

**Comment by vigliensoni** [comment]
I would say one upload button, many formats the user can select with a dropdown menu.

**Comment by fujinaga** [comment]
Ideally, the upload function can figure out what the file format is automatically; but this would be a low priority.

On Aug 12, 2019, at 12:51, Gabriel Vigliensoni <notifications@github.com<mailto:notifications@github.com>> wrote:


I would say one upload button, many formats the user can select with a dropdown menu.

**Comment by ImaneChafi** [comment]
Yeah, we can start with the dropdown menu and change it to make it automatically afterwards. Thank you!
________________________________

**Comment by ImaneChafi** [comment]
Steps to download images and show them in the mei classifier from a word file
1. For the docs files, unzip the file and get the images from the media folder. 
2. Link the images to the columns with the drawing.rels file
3. Store the images in the images collection of Mongodb

**Comment by ImaneChafi** [comment]
You can now upload docx files as html and the neumes will be added to the application with the elements updated : https://github.com/DDMAL/mei-mapping-tool/commit/748bf0d9e15c07f593ce81c60aef11cff4a4951f

**Comment by ImaneChafi** [comment]
For the excel upload, catch the error or give an error message if a person tries to upload a file that doesn't have the right number of columns or the right names.

**Comment by fujinaga** [comment]
What do you mean by “right names”?

On Aug 21, 2019, at 03:08, ImaneChafi <notifications@github.com<mailto:notifications@github.com>> wrote:


For the excel upload, catch the error or give an error message if a person tries to upload a file that doesn't have the right number of columns or the right names.

**Comment by ImaneChafi** [comment]
The name of the fields need to be the same as the ones provided on the example for each column: name, folio, classification, mei.

**Comment by vigliensoni** [comment]
If the names are not the same, you should catch the error, return a warning to the user, and stop processing the file.

**Comment by fujinaga** [comment]
I still don’t understand the name thing.
Do you mean the column headings?

On Aug 21, 2019, at 05:57, Gabriel Vigliensoni <notifications@github.com<mailto:notifications@github.com>> wrote:


If the names are not the same, you should catch the error, return a warning to the user, and stop processing the file.

**Comment by ImaneChafi** [comment]
Exactly! I’ll change the description so that people can understand it better!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fujinaga** [comment]
I don’t think the exact name of the columns matter as long as they are in the pre-defined order.
Also, allow for any row with at least one “valid" entry.
By “valid”, I mean the first column, if present should be an image, and the rest ASCII text.

**Comment by fujinaga** [comment]
This is great!

**Comment by ImaneChafi** [comment]
Perfect! I think the library I’m using skips lines only if they are completely blank so as long as 1 field is valid, the app will upload it as neumes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ImaneChafi** [comment]
There is still a small bug with the images showing from the docx now. The last image is shown, but not the the first pictures
![Uploading Screen Shot 2019-08-29 at 10.14.18 AM.png…]()

**Comment by ImaneChafi** [comment]
<img width="886" alt="Screen Shot 2019-08-29 at 10 14 18 AM" src="https://user-images.githubusercontent.com/46538274/63947982-eaa8dc80-ca45-11e9-8a30-5865e602c3fe.png">

**Comment by ImaneChafi** [comment]
The reason for that might be the values taken from the document.xml file, which doesn't store the rows of tables like the excel files, it stores them from a certain value and keeps incrementing : <wp:docPr id="72" name="Bild 59"/>. The docPr has an id that increments for every row.

**Comment by ImaneChafi** [comment]
I've parsed the html file taken from mammoth and gotten the data from the images. Now all the images are shown on the classifier once you upload a docx file, with the neume data too. There is still some work to do on the indentation of the paragraphs, but the images are shown now when you upload a docx. You might need to reload the page to see all the neumes if the file is very large. https://github.com/DDMAL/mei-mapping-tool/commit/c691f10ffb95fab47d22817a91ff2e7231ed35a6
