### ISSUE TITLE
Declutter file menus

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#115]
As of now, the "file menus" (i.e., Save, Fork, CSV, and Excel) are overlaid on top of the project name. We should declutter this zone. 

![Screen Shot 2019-08-12 at 3 25 28 PM](https://user-images.githubusercontent.com/492229/62892109-6ea85800-bd15-11e9-8cd6-c2005d6b5d2d.png)

**Comment by ImaneChafi** [comment]
Finished : https://github.com/DDMAL/mei-mapping-tool/pull/118
I added a dropdown menu that holds the buttons for CSV download and upload, the save button and the section button
