### ISSUE TITLE
Grab neume from name (blue) zone

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#116]
To drag and drop neumes the user selects the light blue zone. However, the object is actually selected from the bottom part of it and jumps what seems to be the height of the object. The result is that the user doesn't know where the object is actually selected

See the video

https://ddmal.slack.com/files/UAYM9UVM1/FLYK4UKTM/jump.mov

The expected behavior is: the user grabs the neume by the blue zone and drags it until the zone they want.

**Comment by ImaneChafi** [comment]
I changed the handle on the section so that it's always the blue name zone : https://github.com/DDMAL/mei-mapping-tool/commit/eae88e5d7e537be1ab2a9dbfcfca8ea4ac2bb488
