### ISSUE TITLE
Indent code lines properly

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#14]
Make sure you follow indentation and spacing in JavaScript. Each time a new block or block-like construct is opened, the indent increases by two spaces. When the block ends, the indent returns to the previous indent level. The indent level applies to both code and comments throughout the block.

For example, this is hard to read:

https://github.com/DDMAL/mei-mapping-tool/blob/4885003ab4b4a7361e4dabb88df9ade532373977/myapp/public/javascripts/collapsible_element.js#L2-L14

See https://google.github.io/styleguide/jsguide.html#formatting-block-indentation

**Comment by ImaneChafi** [comment]
Yes I'll change the indentation!

**Comment by vigliensoni** [comment]
Great, thanks. Check the style across the entire project and incorporate it in your new code.

**Comment by ImaneChafi** [comment]
Done : https://github.com/DDMAL/mei-mapping-tool/commit/40a9d99457af0a32331e0c4275d7b47fae9bbe15

**Comment by ImaneChafi** [comment]
Corrected the indentation for all the javascript files : https://github.com/DDMAL/mei-mapping-tool/commit/0850bcfd6781bc9ae8458d7fa940f9f6667b1c1c
