### ISSUE TITLE
Show tip or instructions on mouseover

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#145]
A description of the behaviour of the tools in the GUI is needed to help the users to use the app. For example:

![mouseover](https://user-images.githubusercontent.com/492229/63880439-b973d200-c99b-11e9-96bb-4da9a2cb2ca2.png)

**Comment by ImaneChafi** [comment]
Done : https://github.com/DDMAL/mei-mapping-tool/commit/5d7e6a9ecd3e9f576ca956bab59e95876cffdd0a
