### ISSUE TITLE
Fix package file

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#15]
There a few errors when installing the app:

- Unexpected token } in package.json
- Missing package body-parser
- Missing package mongoose
- Missing package bcrypt

**Comment by ImaneChafi** [comment]
The initialization of the app needs to be done in the app folder, by going to the directory `cd mei-mapping-tool/myapp` and then installing the npm with   `npm install` . If npm is called in the mei-mapping-tool/myapp directory, errors will come up.
![Screen Shot 2019-05-29 at 9 19 31 AM](https://user-images.githubusercontent.com/46538274/58560730-b712a800-81f3-11e9-9888-877b8878eb50.png)
