### ISSUE TITLE
Fix format of login page

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#16]
In Safari and Chrome the login page looks pretty weird in a laptop:

<img width="1277" alt="Screen Shot 2019-05-29 at 11 52 31 AM" src="https://user-images.githubusercontent.com/492229/58547827-60fc2f80-8208-11e9-99bb-4df3cfc52862.png">

**Comment by ImaneChafi** [comment]
Yes I'll change the login page for the app!

**Comment by ImaneChafi** [comment]
Fixed! https://github.com/DDMAL/mei-mapping-tool/commit/e01c671e86b8a0e18e956f8dceef8d9f74370f66
