### ISSUE TITLE
some classifier and MEI data needs to be fixed

### ISSUE THREAD

**Issue by suzuka-kokubu** [DDMAL/mei-mapping-tool#161]
There are some incorrect data format on excel file which needs to be fixed

This data is missing /
<img width="1144" alt="Screen Shot 2019-10-28 at 13 23 32" src="https://user-images.githubusercontent.com/55596771/67701360-2b5d9d00-f986-11e9-966b-b1dab50c94d3.png">

The followings needs to have valid encoding MEI instead of sentences.
<img width="1144" alt="Screen Shot 2019-10-28 at 13 19 25" src="https://user-images.githubusercontent.com/55596771/67701033-95297700-f985-11e9-8291-0dcc544673c9.png">
<img width="1144" alt="Screen Shot 2019-10-28 at 13 21 40" src="https://user-images.githubusercontent.com/55596771/67701197-e5083e00-f985-11e9-9024-d8869a24ef49.png">

**Comment by caitlin-hutnyk** [comment]
this is to do with a specific instance of an excel classifier not with cress
