### ISSUE TITLE
Fix a issue with uploading excel file

### ISSUE THREAD

**Issue by suzuka-kokubu** [DDMAL/mei-mapping-tool#162]
unable to upload Neume classifier data (D-KA Aug. LX_Hufnagelschrift_Classifier+MEI.xlsx)

<img width="1065" alt="Screen Shot 2019-10-28 at 13 30 07" src="https://user-images.githubusercontent.com/55596771/67703359-b2f8db00-f989-11e9-9e66-ef10438cac0d.png">

**Comment by vigliensoni** [comment]
I would say this something to do with Nginx in the staging server.

Do you have the same error when you try this on your local version? If not, @deepio may help by adjusting the Nginx config.

**Comment by suzuka-kokubu** [comment]
I was able to upload the excel file on my local version. This issues occurs only on the dev version on https://cress-staging.simssa.ca

**Comment by vigliensoni** [comment]
@suzuka-kokubu Could you please give an estimated size of a large classifier so that @deepio can adjust the Nginx config file in the staging server?

**Comment by deepio** [comment]
Default is 1MB but increased the limit to 27MB.

**Comment by vigliensoni** [comment]
@deepio Any reason for the 27MB? Did @suzuka-kokubu inform you of the maximum size of the classifiers we have? Please add to the Nginx configuration that maximum times two or three.

**Comment by suzuka-kokubu** [comment]
Classifier that I tried to upload yesterday was 4.2MB. Also, thank you for fixing the issue, I was able to upload the same file.

**Comment by deepio** [comment]
@vigliensoni because it would be an oddly specific number someone could look for with grep if they did not know where this setting was for cress. Each server can have it's own limit. `grep -Hnri 27m .` but you're right, I could have just as easily put any number. I don't think something huge like 700MB would be needed for this but we can always change it at any time as our needs grow.

**Comment by vigliensoni** [comment]
@deepio @suzuka-kokubu I checked all the classifiers we have. Currently, the largest (12.4 MB)  we have is `Laon_MEI_29.08.2018_KateAndInga_6.docx`.  The `27 MB` you put will be able to handle a classifier twice as big as this one, and so I think it is going to be fine.
