### ISSUE TITLE
Fix issues with importing classifiers through excel file

### ISSUE THREAD

**Issue by suzuka-kokubu** [DDMAL/mei-mapping-tool#163]
classifier data cannot be correctly imported through excel file as shown below
<img width="966" alt="Screen Shot 2019-10-29 at 12 39 57" src="https://user-images.githubusercontent.com/55596771/67788728-3cbbad80-fa49-11e9-89f2-3aef2b721b16.png">

**Comment by caitlin-hutnyk** [comment]
fixed end of summer 2020
