### ISSUE TITLE
Fix app crash after sign up

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#17]
App returns a 404 and crashes after user tries to sign up 

```
Not Found

404

NotFoundError: Not Found
    at /Users/gabriel/Documents/3_Github/mei-mapping-tool/myapp/app.js:121:8
    . . . 

```

**Comment by ImaneChafi** [comment]
The sign-up page isn't completed yet as I was working on the meiMapping page but I'll add a route for the sign-up right now!

**Comment by ImaneChafi** [comment]
Fixed! Changed the route to project after the user logs-in, will add it to the database : ba17cd97ce68c5f1a75d248d5c5dd17d2ab93d03
