### ISSUE TITLE
Place "New element" modal in foreground

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#19]
Expected behaviour: The "New element" modal should be placed in the foreground.

Current behaviour: As of now, when the user clicks the "plus" icon to add glyphs, the modal not placed in the foreground, so that part of the ACE editor as well as the images or overlaid on top of the menu.

<img width="920" alt="Screen Shot 2019-05-30 at 9 20 50 AM" src="https://user-images.githubusercontent.com/492229/58615950-b09c3300-82bc-11e9-90cb-9f822b9beb41.png">

**Comment by ImaneChafi** [comment]
Perfect I'll change it so that it's in the foreground!

**Comment by ImaneChafi** [comment]
It's in the foreground now : https://github.com/DDMAL/mei-mapping-tool/commit/75496da232b6ac6df54d83b0a2eee0a91fd19456
