### ISSUE TITLE
Remove modules in node_modules from repo

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#2]
Unless you have a strong reason to do this, files from node_modules should not be part of the repo. ```npm``` can resolve dependencies for the packages you need.

**Comment by deepio** [comment]
Exactly, this is also what the `package-lock.json` file is for because it stores a hash for each package.

**Comment by vigliensoni** [comment]
@ImaneChafi, any reason why this has not being fixed?

**Comment by ImaneChafi** [comment]
The node modules were deleted from the repository : https://github.com/DDMAL/mei-mapping-tool/commit/45dec3f3d75952ad8e9262ba6d118c06abce434f

**Comment by vigliensoni** [comment]
They are still there, twice. One at the root level, one at the myapp level. We should not comit these.

**Comment by ImaneChafi** [comment]
Yes I will delete them again!

**Comment by vigliensoni** [comment]
Also, add the folder to .gitignore

**Comment by ImaneChafi** [comment]
Here are the commits for the node modules : https://github.com/DDMAL/mei-mapping-tool/commit/12c098ecfd531eec82e6c171647883f30441dff4 and the gitignore : https://github.com/DDMAL/mei-mapping-tool/commit/3be1ba2a1abbe2991e14252bbed3e989ed5d1074
