### ISSUE TITLE
when importing an xlsx file, Cress does not upload entries in the same order as the xlsx/csv files

### ISSUE THREAD

**Issue by thesoundbyle** [DDMAL/mei-mapping-tool#223]
It seems that when importing a file into CRESS, the order of the assets in the Project does not respect the order in the excel file.

**Comment by evansavage** [comment]
This has been sorted out using JS promises (calling `await` within asynchronous functions). It was due to database saves being called on top of one another and not waiting for the last one to complete.

**Comment by thesoundbyle** [comment]
Issue no longer occurs, closing ticket
