### ISSUE TITLE
Side menu toggle is not functional

### ISSUE THREAD

**Issue by thesoundbyle** [DDMAL/mei-mapping-tool#229]
The side menu button will only toggle its icon, with nothing  else occurring

![Screenshot_2](https://user-images.githubusercontent.com/62864127/119863216-548a3a80-bee7-11eb-9eaf-e2389cb27773.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/62864127/119863217-5522d100-bee7-11eb-864a-9fb57c56f1c6.jpg)

**Comment by evansavage** [comment]
I've commented this out for the time being
