### ISSUE TITLE
When clicking the username button in the projects page, the user will be navigated to an error page

### ISSUE THREAD

**Issue by thesoundbyle** [DDMAL/mei-mapping-tool#230]
![Screenshot_4](https://user-images.githubusercontent.com/62864127/119863347-72f03600-bee7-11eb-9782-63c3793d99f5.jpg)

**Comment by evansavage** [comment]
This is due to a routing error. There is an 'add collaborator' function on the user profile that is not working correctly.

**Comment by evansavage** [comment]
I've commented out the corresponding code on the template. We can track a new error for the collaborator function if it is to be reestablished in the new version.

**Comment by thesoundbyle** [comment]
Issue no longer occurs, clicking the username now leads to the "profile" page. 
but it would be nice if the profile button was available on every page not just in a project (should i write a new issue for this?)
