### ISSUE TITLE
Add view for the neume images

### ISSUE THREAD

**Issue by ImaneChafi** [DDMAL/mei-mapping-tool#25]
The neume images are currently being redirected to a gallery in the localhost:300/gallery page. We want to have a view to see the neume images identified next to the names and classifications from the database, as seen in the google docs the musicologists sent us.

**Comment by ImaneChafi** [comment]
Added the view for a picture for each neume, need to change it for multiple images for each neume : https://github.com/DDMAL/mei-mapping-tool/commit/2b81ec005e7b14474acd98b83ea6b999edcc951b

**Comment by ImaneChafi** [comment]
Added view for deleting the neumes and updating them based on the name of the neumes : https://github.com/DDMAL/mei-mapping-tool/commit/5548713d3684b62436976692cc815c868f2ec520
Question : Can we have a neume element with no pictures and only the name of the neume, or is the image a required field?

**Comment by fujinaga** [comment]
Image is always required but the user may not have the required image at the moment. So I would suggest inserting an image temporarily indicating that the image needs to be eventually inserted.


On Jun 10, 2019, at 13:14, ImaneChafi <notifications@github.com<mailto:notifications@github.com>> wrote:


Added view for deleting the neumes and updating them based on the name of the neumes : 5548713<https://github.com/DDMAL/mei-mapping-tool/commit/5548713d3684b62436976692cc815c868f2ec520>
Question : Can we have a neume element with no pictures and only the name of the neume, or is the image a required field?

**Comment by ImaneChafi** [comment]
Perfect thank you!

**Comment by ImaneChafi** [comment]
The images collection is linked to the neumes collection with the image path : https://github.com/DDMAL/mei-mapping-tool/commit/e50ef70c962d45d8246f7adbeee46584e9cf64ac

**Comment by DDMAL-LabManager** [comment]
I don't see what we gain by inserting a “temporary” image instead of having an empty field. From the retrieval perspective, it will be much easier to search for rows that do not have any image associated with it.

**Comment by fujinaga** [comment]
No strong preference. I suggested "temporary" image thinking that it may be easier to program.

**Comment by ImaneChafi** [comment]
It's okay! I can also hide the image field such that even if there is no image, there won't be an empty field that will show up in the app.

________________________________

**Comment by vigliensoni** [comment]
I think it's ok that you display an empty field. That will help users to know they need to add those images.

**Comment by ImaneChafi** [comment]
Okay! I'll change it now!

________________________________

**Comment by ImaneChafi** [comment]
Done : both for the edits and the add new neume, you can add new neume images to the view and see all images for a neume under the show page: https://github.com/DDMAL/mei-mapping-tool/commit/bac9913977f576b03f6c0cd43a5aa167fb1bde27
