### ISSUE TITLE
Catch wrong email or password

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#26]
If a user enters a wrong email or password when logging in, the app renders a new page with the debugging trace. We should only display a warning and stay in the same page.

![Screen Shot 2019-06-11 at 9 18 30 AM](https://user-images.githubusercontent.com/492229/59275230-e8df3200-8c29-11e9-87a9-4dc301922c22.png)

**Comment by ImaneChafi** [comment]
Done : https://github.com/DDMAL/mei-mapping-tool/commit/b5ea1e00b9423099bf855759a7dfa375c8bcd103
