### ISSUE TITLE
Add image filepath to database

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#27]
The filepath of images should be stored in the database collection.

**Comment by ImaneChafi** [comment]
The images accepted are now : .png, .jpg, .tiff, .tif, and .jpeg : https://github.com/DDMAL/mei-mapping-tool/commit/796492ada17697665091a463d41c5965b9191d0b

**Comment by ImaneChafi** [comment]
Added filepath of images in the images collection : https://github.com/DDMAL/mei-mapping-tool/commit/351f34ef7505749298f1c4652f75a810f9a5b77c

Each image has a unique Id which will be used to link the neumes collection to the image collection.
