### ISSUE TITLE
Create uploads folder to store images

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#29]
```Uploads``` folder is currently part of .gitignore. Make sure you create it if it does not exist.

**Comment by vigliensoni** [comment]
This is linked to the error message that Dropzone displays when uploading images

![Screen Shot 2019-06-11 at 9 46 36 AM](https://user-images.githubusercontent.com/492229/59277278-e8489a80-8c2d-11e9-80cf-1f795bc9b80a.png)

**Comment by ImaneChafi** [comment]
Created uploads folder from the beginning of the app if the folder doesn't exist : https://github.com/DDMAL/mei-mapping-tool/commit/2303954099e3fcb8585f5ece6dcadb8eea928bce
