### ISSUE TITLE
Move file structure to root of repository

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#3]
Unless you have a strong reason for having all your code inside a folder, there is no need of having the ```Website_SIMSSA``` folder in the repository.

**Comment by ImaneChafi** [comment]
I moved the files from the Website_SIMSSA to the repository and deleted the Website_SIMSSA folder :  https://github.com/DDMAL/mei-mapping-tool/commit/9ada2456785f4b3512b38f3be2450dd13b533509
