### ISSUE TITLE
Create view for displaying all neumes in project

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#32]
Similar to what you had before, and actually equal to the classifiers you have.

**Comment by ImaneChafi** [comment]
I added the view for the images based on the database. The images are linked to the neumes collection and when they are added to the dropzone, they are added to the array of images inside of the collection. The images are then used depending on the neume to be displayed on the show page.  Question : Should the uploads folder be created with the images from the database or should it be created beforehand, and afterwards when each image is uploaded to the database the uploads folder automatically receives the image path from the database?

**Comment by vigliensoni** [comment]
If you don't create it beforehand, you have to check if it exists first. If it doesn't create it. Otherwise, just create it, add it to the repo, but don't commit the images (e.g., add a filter to the .gitignore file)

**Comment by ImaneChafi** [comment]
Perfect, that's what I did thank you!

**Comment by ImaneChafi** [comment]
Done : https://github.com/DDMAL/mei-mapping-tool/commit/67c0a57038ddeb98f218944c9c86c6638f05bef4

There is still something to be changed about the pages needed to be reloaded twice to see the neumes, I will change it right now!

**Comment by ImaneChafi** [comment]
Finished : You can update neumes, delete them and create new ones depending on the projects you are in and they will be labeled differently in the database based on the project id. https://github.com/DDMAL/mei-mapping-tool/commit/c8f29da846b42cc032610badc83330932ffd2a5b
