### ISSUE TITLE
Update modules needed

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#37]
When trying to run ```create_neume_view``` branch there are still modules that the app can't find (e.g., alert-node)

**Comment by ImaneChafi** [comment]
Can you send me a screenshot of the error you got from the node-modules? I re-cloned the repository to see if there would be any error but all the modules were downloaded when the npm start was made on the mei-mapping-tool.
<img width="597" alt="Screen Shot 2019-07-05 at 4 18 29 PM" src="https://user-images.githubusercontent.com/46538274/60743810-20977c00-9f41-11e9-914e-c3509a3352f4.png">

**Comment by ImaneChafi** [comment]
Alert-node has been uninstalled.
