### ISSUE TITLE
Use collections instead of many databases

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#4]
Unless you have a strong reason for using several databases, you should just use one database with different collections to manage users and projects.

https://docs.mongodb.com/manual/core/databases-and-collections/

**Comment by ImaneChafi** [comment]
Perfect! I've deleted the previous projects database and made a collection instead : https://github.com/DDMAL/mei-mapping-tool/commit/c302e0b8ecf59d010b26ef98c51a9f23b7f14373
