### ISSUE TITLE
Catch error when duplicated email is used.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#40]
If a user uses an email twice an error is thrown:

E11000 duplicate key error collection: mei-mapping-tool.users index: email_1 dup key: { : "my@email.com" }

The error message should be something like: "Email already used." If that is the case, you should provide the functionality to recover the password. That is, implement the same behaviour you expect in any web service.

**Comment by vigliensoni** [comment]
Same happens with the same username.

**Comment by ImaneChafi** [comment]
Done for the username or email : https://github.com/DDMAL/mei-mapping-tool/commit/41797c160dbaa97bb996908aa7e40830de452943
