### ISSUE TITLE
Prevent db to save code snippet if is not valid XML

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#44]
Ideally, we should check for MEI.

**Comment by vigliensoni** [comment]
Thinking a bit more about this, the classifier could be used to try things out, and so it is possible the encoding is not yet ready. 

We should validate all the encodings in a subsequent step, upon the request of the user.

**Comment by ImaneChafi** [comment]
I can make a checkbox if the user wants its mei code to be validated such that the form can still be submitted. There will be a small message next to the neume that says "under review".

**Comment by ImaneChafi** [comment]
Added under review model and button that takes information from the database whether the user wants to have it's code under review. Also, when someone updates a neume, they can also update whether they want to have their code under review.

**Comment by ImaneChafi** [comment]
https://github.com/DDMAL/mei-mapping-tool/commit/264311ad9043dfd5365efc3c1c61b31c895b5caa

**Comment by ImaneChafi** [comment]
If the user says that their code needs to be reviewed and it has errors, then they will be able to submit their new neume. However, if the user says that their code doesn't need to be reviewed and it has errors, then they will not be able to submit their new neume. The check is done in xml. I am working on using neon's worker to implement it to check for mei. https://github.com/DDMAL/mei-mapping-tool/commit/f14bbc11f335bd1388f84f60f67243f0ad44bb35

**Comment by ImaneChafi** [comment]
Done on the update page too : https://github.com/DDMAL/mei-mapping-tool/commit/08470c916c4e48ffa03b7c00343abf7bfd8cd580
