### ISSUE TITLE
Preserve image proportions.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#45]
Do not scale images to make them squared, it's pretty difficult to see the actual content if you do so. See the third image of the screenshot:

![Screen Shot 2019-07-04 at 3 25 18 PM](https://user-images.githubusercontent.com/492229/60685236-f2963700-9e6f-11e9-81c6-038239e0985a.png)

**Comment by ImaneChafi** [comment]
Yes I will change it so that it keeps the proportions.

**Comment by ImaneChafi** [comment]
Done : https://github.com/DDMAL/mei-mapping-tool/commit/8040673f8749bc7d8a227fef3eb3ac10bda72a75
