### ISSUE TITLE
Delete image from database after deleting from UI.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#46]
If a user goes into "Edit Images" and clicks in any of the "x" for deleting an image, the app goes back to project view and the image is still present.

**Comment by ImaneChafi** [comment]
Works now! Deleted both from the image view and the neume array in the database : https://github.com/DDMAL/mei-mapping-tool/commit/8b9b07dfddab5b53060ac49644c96a25c29f20e6
