### ISSUE TITLE
Clean registration form after registration.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#47]
If the user goes back to the landing page after logging out, the registration form has wrong default information:

E-mail field: empty (fine)
Username: loaded with previous email (wrong)
Password: previous password (wrong)
Confirm Password: empty (fine)

**Comment by ImaneChafi** [comment]
Should the registration form have no default information or should it have examples of information to use? (like ex. 123@gmail.com)

**Comment by ImaneChafi** [comment]
Done : I added a pop-up message instead of changing pages if the username or email for registration is already taken. https://github.com/DDMAL/mei-mapping-tool/commit/41797c160dbaa97bb996908aa7e40830de452943
