### ISSUE TITLE
Restrict access to projects.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#48]
Users should only be able to edit projects that they created, or that they are assigned to.

With the current behaviour, registered users can edit all projects.

**Comment by ImaneChafi** [comment]
I'll change the registration right away. To assign the projects, I will add a feature under the database model.

**Comment by ImaneChafi** [comment]
Done, the projects created by the user are the only ones that can be seen! : https://github.com/DDMAL/mei-mapping-tool/commit/c890c0e80db48b34f977f8a071c1dfa5154f72a4

**Comment by ImaneChafi** [comment]
You can now add users under mongoDB to projects in the array of userIDs : https://github.com/DDMAL/mei-mapping-tool/commit/cce4aa4c85a0ac0ea99b29b81ac63ae29aa03650

**Comment by vigliensoni** [comment]
I don't understand what you are saying.

**Comment by ImaneChafi** [comment]
When users register and log-in, the projects they create are the only ones they can access. I've also added a schema under the projects collection to add users to projects if multiple users want to work on the same project. This access can only be done through mongodb.

**Comment by ImaneChafi** [comment]
Finished : https://github.com/DDMAL/mei-mapping-tool/commit/1556163694dcd7b7a6c0b4e3666c2401f05d5afc
Users can now access the projects and see the neumes without being able to edit them if they did not register.
