### ISSUE TITLE
Add installation instructions.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#5]

**Comment by vigliensoni** [comment]
Could you please add a few instructions to run the app locally?

**Comment by ImaneChafi** [comment]
Yes! I will update the wiki with the information on how to run the add locally.

**Comment by ImaneChafi** [comment]
I updated the README.md : https://github.com/DDMAL/mei-mapping-tool/commit/a54d582907061932c7500c2c3d192fd473012c3d

**Comment by vigliensoni** [comment]
These instructions will only work if the user get rid of the ```node_modules``` folder, otherwise there will a "ELOOP: too many symbolic links encountered" error.

Also, there are missing instructions for installing mongodb and have it running as a service.

**Comment by ImaneChafi** [comment]
Perfect I'll change that now in the README.md

**Comment by ImaneChafi** [comment]
Here is the commit for the new README.md updated with the mongodb info : https://github.com/DDMAL/mei-mapping-tool/commit/4cf92ff717cb6b56423ffa43351d157081cba322
 I also updated the gitignore for the nodemodule folder to be ignored : https://github.com/DDMAL/mei-mapping-tool/commit/80b288431ed80fb288fda9a6e5a01830189931f6 . Does the previous error of 'ELOOP: too many symbolic links encountered' still occur?

**Comment by vigliensoni** [comment]
There are some extra packages that need to be added to the dependencies of the project. Otherwise, people will need to add them in addition:

body-parser
bcrypt
mongoose

Also, make sure people is actually running mongodb. If installed using homebrew: ```brew services start mongodb```

**Comment by ImaneChafi** [comment]
I'll add it to the README.md! Also, the collapsible elements work with the add button : https://github.com/DDMAL/mei-mapping-tool/commit/af9d8b58ada3b0b233236c0b88171c82f41ba19d

**Comment by ImaneChafi** [comment]
You can now sign-up with another username and password and create your own account for the mei-mapping to use in the log-in page. No need to use the default username and password anymore : https://github.com/DDMAL/mei-mapping-tool/commit/74fb2fc68972c550a22a83adb410b54637afac1d

**Comment by ImaneChafi** [comment]
Updated : https://github.com/DDMAL/mei-mapping-tool/commit/88bf3edfe48aa55787113454e8cb374aef7603c6
