### ISSUE TITLE
Change user 'type' to 'role'.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#6]
Use variables names that are more descriptive of what you want to describe. In this case, you are trying to describe the role of the user (i.e., admin, editor, or viewer)

https://github.com/DDMAL/mei-mapping-tool/blob/b42ee23c9abf824e80f35514e9189971dcfcb92b/myapp/app.js#L35-L39

**Comment by ImaneChafi** [comment]
Perfect, I've changed the name to role : https://github.com/DDMAL/mei-mapping-tool/commit/889fe76126b92ba030fc4051db5207aa649fafd7
