### ISSUE TITLE
Add ace editor to mei encoding

### ISSUE THREAD

**Issue by ImaneChafi** [DDMAL/mei-mapping-tool#8]

**Comment by ImaneChafi** [comment]
Ace editor works now : https://github.com/DDMAL/mei-mapping-tool/commit/e855aba70c860315ab3a74d82d324567946f466f 
I just need to add the highlighted text!

**Comment by ImaneChafi** [comment]
Here is the commit for the highlighted syntax now working : https://github.com/DDMAL/mei-mapping-tool/commit/d0609d7544fc0fc661711225efbbac5a28434044

**Comment by vigliensoni** [comment]
🥇 👍
