### ISSUE TITLE
Improve app layout

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#89]
Layout of the classifier should be improved in order to optimize the space on the screen.

- [x] "Save as" and "Project CSV file" can be closer to the project name, on the same line, justified to the right.
- [x] Write a common label for each of the columns, so that we don't need to have column names in within each column.
- [x] Since the user can update information on the screen by pressing "Return" (macOS and Safari), it seems we don't need the "Update name" button.
- [x] In the second column get rid of "Name:" (since this name is exactly the same as on the blue line) 
- [x] In the second column, have the folio and description text entry in the same line
- [x] In the third column get rid of "Classification".
- [x] Label the fourth column "MEI Encoding" and get rid of the description and "model to follow". Put those in the instructions.
- [x] The MEI Encoding column needs to be wider than the other ones.
- [x] Organize and place the "Update" and "X" buttons closer to the neume object they are associated with (i.e., same line)

**Comment by ImaneChafi** [comment]
Done : https://github.com/DDMAL/mei-mapping-tool/pull/92

**Comment by vigliensoni** [comment]
This is a great improvement!

Could you please:

- [ ] Reduce the height of the header, so that there is more space when landing on the page.
- [ ] Change the z-index of "Edit", "Fork", and "CSV" buttons so that these get rendered behind the table labels?
- [ ] Decrease the font size of the classification column, so that it is the same as the other columns.
- [ ] Change the zone of "Needs review"? This one is responsible for a large portion of blank space on the page. It could be just a small toggle.

**Comment by ImaneChafi** [comment]
Done : https://github.com/DDMAL/mei-mapping-tool/pull/95
