### ISSUE TITLE
Finish Post request for the drag and drop to store multiple images

### ISSUE THREAD

**Issue by ImaneChafi** [DDMAL/mei-mapping-tool#9]

**Comment by ImaneChafi** [comment]
The dropzone is made using a form and the database uses forms as the posting options for sending data in collection. I can make 2 collections, one for the dropzone images and one for the neume info and link the databases together based on unique ids I can add to them.

**Comment by vigliensoni** [comment]
What are the advantages of having two collections instead of just one?

**Comment by ImaneChafi** [comment]
The drop zone is written as a form, and if I try to put the drop zone and the rest of the elements inside of another form that holds the post request, the drop zone stops working. However, I can make 2 collections, one to hold the post request for the drop zone and another for the rest of the neume component and link the two collections together when the save button is pressed.

Best regards,
Imane Chafi

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ImaneChafi** [comment]
The information is now all stored in the database collection in a single schema for the neumes with sections for the name, classifier, folio and ace editor. I am finishing the get requests to post the ace editor values on the screen from the database even if the user refreshes the page.

**Comment by ImaneChafi** [comment]
Finished the post request for the dropzone : https://github.com/DDMAL/mei-mapping-tool/commit/073cb3439c06b243e8a29d06ad934a0782b69afd
The images are stored in the uploads folder once they are added to the dropzone
