### ISSUE TITLE
Fix image upload and delete

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/mei-mapping-tool#90]
There is some strange behaviour when adding and deleting images. Sometimes all of them dissapear after deleting one of them. 

See the video linked in the image (need to be signed into Slack)

[![Screen Shot 2019-07-29 at 2 10 32 PM](https://user-images.githubusercontent.com/492229/62071502-a9d16400-b20a-11e9-8376-44411acacaf9.png)](https://ddmal.slack.com/files/UAYM9UVM1/FLX7DQV63/images.mov)

**Comment by caitlin-hutnyk** [comment]
this was fixed at some point in the refactoring during summer 2020
